# Generated by Django 4.2.7 on 2023-11-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='uncategorized', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
